### ISSUE TITLE
Control the separation (padding or margin?) between interior cards

### ISSUE THREAD

**Issue by arigit** [custom-cards/vertical-stack-in-card#46] opened 2019-01-30 05:57 UTC
My use case: I use vertical-stack-in-card to stack 'entities' cards, one of which is conditional (so it appears or disappears depending on the state of a switch).

The case works fine however there is a very large amount of padding between the adjacent 'entities' cards; ideally the separation between the last entity of the first card and the first entity of the second card should be the standard separation between entities within a normal card. Currently that separation is a lot more than that:

![image](https://user-images.githubusercontent.com/652673/51961204-f689dd00-2429-11e9-9074-1fb0823ede1b.png)

Is it possible to make this separation a parameter so we can reduce it and make stacking of entities cards more 'normal'

**Comment by ofekashery** [comment] 2019-01-30 06:01
Duplicate of #20

**Closed by ofekashery** 2019-01-30 06:01 UTC
